# Generated by Django 4.2.11 on 2024-06-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="remark",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
