# Generated by Django 4.2.11 on 2024-06-17 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_user_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abn_income",
            name="form_date",
        ),
        migrations.AddField(
            model_name="abn_income",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="abn_income",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[("Mr", "Mr"), ("Mrs", "Mrs"), ("Ms", "Ms")],
                max_length=5,
                null=True,
            ),
        ),
    ]
