# Generated by Django 4.2.11 on 2024-06-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_remove_abn_income_form_date_abn_income_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abn_income",
            name="grossincomereceivedinbank",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spouse",
            name="spouse_taxable_income",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
