# Generated by Django 4.2.11 on 2024-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_abn_income_grossincomereceivedinbank_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tfn",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
