# Generated by Django 4.2.11 on 2024-06-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_alter_user_tfn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abn_income",
            name="abn",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="dateofbirth",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="tfn",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[("Mr.", "Mr."), ("Mrs.", "Mrs."), ("Ms.", "Ms.")],
                max_length=5,
                null=True,
            ),
        ),
    ]
