# Generated by Django 4.2.11 on 2024-06-25 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_abn_income_abn_alter_user_dateofbirth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport_drivinglicense",
            name="passport",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user/documents",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf", "docs"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="supportingdocuents",
            name="supportingdocuments",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user/documents",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf", "docs"]
                    )
                ],
            ),
        ),
    ]
